### PR TITLE
Update mailparser.js

### PR DESCRIPTION
**Pull request by runfan**
修复在解决中文邮件的时候出现乱码的情况

### CODE REVIEW

**Comment by andris9** [comment]
Could you provide an example email where this is an issue? Current behavior prefers charsets defined in HTML source to the charset defined in the header.

**Comment by runfan** [comment]
Subject: =?UTF-8?B?UmU6IOmVv+aXuu+8jOWFs+S6juS9oOeahOW3peS9nA==?=
To: "" <tt@qq.com>
References: <201510241556538367697@qq.com>
From: test@qq.com
Message-ID: <562CB66B.6060409@qq.com>
Date: Sun, 25 Oct 2015 19:00:59 +0800
MIME-Version: 1.0
In-Reply-To: <201510241556538367697@qq.com>
Content-Type: text/html; charset=gbk
Content-Transfer-Encoding: 8bit

<html><head>
  <meta charset="utf-8">
  <title></title>
  <style></style>
</head>
<body>哨子邮件<span style="font-family:SimSun;"><span style="font-size:14px;"><span style="color:#000000;"><span style="background-color:#FFFFFF;"></span></span></span></span>整体相当于是从头开始做，在新的东西出来之前，旧的东西不会有任何的改进。<br>我已经没有在旧的内容上提交过代码了。<br> 
<pre class="moz-signature" cols="72">
258集团--用会思考的互联网连接企业一切
-------------------------------
邮箱：test@qq.com
集团官网 http://www.258jituan.com 
地址：中国厦门市湖里区万达写字楼C2栋12楼
【 厦门二五八集团有限公司 】</pre></body></html>

**Comment by andris9** [comment]
Just to clarify, as it can not be detected from the pasted email, is the HTML content using UTF-8 as declared in the HTML header or is it using GBK as defined in the MIME header? Without your change, mailparser would prefer UTF-8 as declared in HTML, with your change it would prefer GBK from the MIME header.

**Comment by runfan** [comment]
我的邮件源文是以 gbk 编码的，所以在MIME header中使用的 gbk ，但是 html 中使用的编码是 utf-8 。如果以 utf-8 编码来对邮件的正文进行解码，所有带中文的地方就会出现乱码。

**Comment by andris9** [comment]
Ok, I think you're right. If I think of it, then MIME header defines the encoding of the container, not the contents, so it should be preferred.

**Comment by andris9** [comment]
Published to npm as v0.5.3

**Pull request merged**
