### PR TITLE
Update node-uue for better support of parsing uuencoded attachments

### PR DESCRIPTION
**Pull request by deepwell**
Update the node-uue library for better parsing of uuencoded attachments.

### CODE REVIEW

**Comment by deepwell** [comment]
Looks like it bumps the minimum node.js version to 0.10, not sure if you're okay with that.

**Comment by andris9** [comment]
uuencode support is not in great demand, so if there isn't any substantial bugfixes in the uue module, I wouldn't upgrade at this point. In the long term it doesn't make much sense to keep supporting Node v0.8 but dropping support for such unimportant change doesn't seem right either.

**Comment by deepwell** [comment]
I forgot to mention I'd really like this update because it fixes a crash for me on mail import. I've seen this a few times now and would like this fixed.

Here's the node.js crash output:
```
crypto.js:240
  this._binding.update(data, encoding);
                ^
TypeError: Not a string or buffer
    at Hash.update (crypto.js:240:17)
    at MailParser._finalizeContents (/Users/deepwell/ws/lib/node_modules/mailparser/lib/mailparser.js:902:40)
    at MailParser._processStateBody (/Users/deepwell/ws/lib/node_modules/mailparser/lib/mailparser.js:389:26)
    at MailParser._process (/Users/deepwell/ws/lib/node_modules/mailparser/lib/mailparser.js:233:22)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The options I see are:
1) Wait until you're comfortable merging this into mailparser
2) Use my forked version of mailparser with this patch applied

What do you recommend?

**Comment by andris9** [comment]
Yeah, I guess supporting 0.8 is an overkill by now. I upgraded all dependencies to latest and pushed as v0.5.0

**Comment by deepwell** [comment]
Thanks!

**Pull request merged**
