### PR TITLE
Fixes the issue of parsing mails with additional plain text

### PR DESCRIPTION
**Pull request by tajinder**
Most of the times emails are sent with content in both and specified as alternate (reader can use either one). 
However for some cases it's not an alternate view, but additional content, and we need to join the plain and html.

### CODE REVIEW

**Comment by andris9** [comment]
Thanks!

**Comment by tajinder** [comment]
Can you release a new version with my fix in it ?

**Comment by andris9** [comment]
Sorry, released as v0.6.0 just now

**Comment by tajinder** [comment]
Thanks :)

**Pull request merged**
